# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32bf3ed8f1903eeb4d8004db0a662e932a24dbebd29b159de862f45e44f5904e5bddf3f11f945b15d850d113e3a35af434fb646d1ab2064148ca1731db06505f

test:
  secret_key_base: 2e57fa63ce7c180d5a191726a3b579ed0dcc808afd291aa6c0bbd6d6d17334ea6c7a767e1d221b68d7da360cd80e22403209f6943b3827d683cab4dade230c3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
